name: Deploy Backend to AWS

on:
  push:
    branches: [ main ]
    paths: [ 'API/**' ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      working-directory: API
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG} -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Deploy to App Runner (manual trigger)
      if: ${{ success() }}
      env:
        SERVICE_ARN: ${{ secrets.APP_RUNNER_SERVICE_ARN }}
      run: |
        if [ -z "$SERVICE_ARN" ]; then
          echo "APP_RUNNER_SERVICE_ARN secret is not set."
          exit 1
        fi
        for attempt in {1..8}; do
          if aws apprunner start-deployment --service-arn "$SERVICE_ARN"; then
            exit 0
          fi
          sleep 15
        done
        echo "Failed to start App Runner deployment after multiple attempts"
        exit 1
