name: Deploy Backend to AWS

on:
  push:
    branches: [ main ]
    paths: [ 'API/**' ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Debug: List current directory contents
        echo "Current directory:"
        pwd
        ls -la
        
        # Navigate to API directory (since this is a backend-only repo)
        echo "Found API directory in root"
        cd API
        
        # Build and push images
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to App Runner
      id: deploy-apprunner
      run: |
        # Function to attempt deployment with retries
        attempt_deployment() {
          local max_attempts=5
          local attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "Deployment attempt $attempt of $max_attempts"
            
            # Check service status immediately before deployment attempt
            SERVICE_STATUS=$(aws apprunner describe-service \
              --service-arn ${{ secrets.APP_RUNNER_SERVICE_ARN }} \
              --query 'Service.Status' --output text)
            
            echo "Service status: $SERVICE_STATUS"
            
            if [ "$SERVICE_STATUS" = "RUNNING" ]; then
              echo "Service is running, attempting deployment..."
              
              # Try to start deployment and capture the result
              if aws apprunner start-deployment --service-arn ${{ secrets.APP_RUNNER_SERVICE_ARN }}; then
                echo "Deployment started successfully!"
                return 0
              else
                echo "Deployment failed, checking if it's a race condition..."
                sleep 10
              fi
            elif [ "$SERVICE_STATUS" = "CREATE_FAILED" ] || [ "$SERVICE_STATUS" = "DELETE_FAILED" ]; then
              echo "Service is in failed state: $SERVICE_STATUS"
              exit 1
            else
              echo "Service not ready (status: $SERVICE_STATUS), waiting..."
              sleep 30
            fi
            
            attempt=$((attempt + 1))
          done
          
          echo "Failed to start deployment after $max_attempts attempts"
          return 1
        }
        
        # Wait for service to be ready, then attempt deployment
        echo "Waiting for App Runner service to be ready for deployment..."
        
        for i in {1..24}; do  # Wait up to 12 minutes
          SERVICE_STATUS=$(aws apprunner describe-service \
            --service-arn ${{ secrets.APP_RUNNER_SERVICE_ARN }} \
            --query 'Service.Status' --output text)
          
          echo "Check $i: Service status is $SERVICE_STATUS"
          
          if [ "$SERVICE_STATUS" = "RUNNING" ]; then
            echo "Service is ready, attempting deployment..."
            if attempt_deployment; then
              echo "Deployment initiated successfully!"
              exit 0
            fi
          elif [ "$SERVICE_STATUS" = "CREATE_FAILED" ] || [ "$SERVICE_STATUS" = "DELETE_FAILED" ]; then
            echo "Service is in failed state: $SERVICE_STATUS"
            exit 1
          fi
          
          if [ $i -eq 24 ]; then
            echo "Timeout waiting for service to be ready for deployment"
            exit 1
          fi
          
          sleep 30
        done
